// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from license_utils.djinni

#import "XBNBLicenseStatus.h"
#import <Foundation/Foundation.h>
@class XBNBLicenseManager;


/** This class incapsulates information about Client Token. */

#ifndef DJINNI_EXPORT
    #define DJINNI_EXPORT __attribute__((__visibility__("default")))
#endif

DJINNI_EXPORT
@interface XBNBLicenseManager : NSObject

/** Creates *new* `LicenceManager`. This metod won't change Banuba SDK internal state. */
+ (nullable XBNBLicenseManager *)create:(nonnull NSString *)clientToken;

/**
 * Returns the instance used by Banuba SDK to check licence.
 * This istance was created by `UtilityManager.initialize`.
 */
+ (nullable XBNBLicenseManager *)instance;

/** Checks if Client Token is expired. */
- (XBNBLicenseStatus)isExpired;

/** Returns decoded content of Client Token */
- (nonnull NSString *)getJson;

/** Returns hash of Client Token */
- (nonnull NSString *)getChecksum;

@end
