// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from license_utils.djinni

#import <Foundation/Foundation.h>
@class BNBAliasLicenseManager;


@interface BNBAliasInformer : NSObject

/** Send event to Banuba Servers with custom key and value */
+ (void)sendEvent:(nullable BNBAliasLicenseManager *)manager
              key:(nonnull NSString *)key
            value:(nonnull NSString *)value;

@end
