/// \file
/// \addtogroup LicenseUtils
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from license_utils.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>
#include <string>

namespace bnb { namespace interfaces {

class alias_license_manager;

class BNB_EXPORT alias_informer {
public:
    virtual ~alias_informer() {}

    /** Send event to Banuba Servers with custom key and value */
    static void send_event(const std::shared_ptr<alias_license_manager> & manager, const std::string & key, const std::string & value);
};

} }  // namespace bnb::interfaces
/// @}

