// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from license_utils.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, XBNBLicenseStatus)
{
    /** everything is ok */
    XBNBLicenseStatusValid,
    /** canceled by Banuba */
    XBNBLicenseStatusRevoked,
    /** before begin time or expired */
    XBNBLicenseStatusTimeBombed,
};
